# this file is included by CMF Routing
Netgen\Bundle\LayoutsRoutingBundle\Entity\Content:
    definitions:
        main:
            uri_schema: /page/{name}
            defaults:
                _type: view
    token_providers:
        name: [content_method, {method: getName, slugify: true}]
    conflict_resolver: auto_increment
    defunct_route_handler: leave_redirect
